---
- name: Create element directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0750"
  loop:
    - "{{ element_data_dir }}"

- name: Deploy element compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ element_data_dir }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    mode: "0640"
  notify: restart element

- name: Start element stack
  community.docker.docker_compose_v2:
    project_src: "{{ element_data_dir }}"
    state: present
