version: "2.3"

services:
  backup:
    image: ghcr.io/realorangeone/db-auto-backup:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /docker/Data/Backups:/var/backups
    environment:
      - HEALTHCHECKS_ID=
      - HEALTHCHECKS_HOST=
