---
- name: Create netbox directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0750"
  loop:
    - "{{ netbox_data_dir }}"

- name: Deploy netbox compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ netbox_data_dir }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    mode: "0640"
  notify: restart netbox

- name: Start netbox stack
  community.docker.docker_compose_v2:
    project_src: "{{ netbox_data_dir }}"
    state: present
