---
- name: Create wiki_js directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0750"
  loop:
    - "{{ wiki_js_data_dir }}"

- name: Deploy wiki_js compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ wiki_js_data_dir }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    mode: "0640"
  notify: restart wiki_js

- name: Start wiki_js stack
  community.docker.docker_compose_v2:
    project_src: "{{ wiki_js_data_dir }}"
    state: present
