networks:

  Public:
    name: Public
    external: true

services:
  pds:
    image: ghcr.io/bluesky-social/pds:latest
#    user: "{{ docker_user.id }}"
    restart: unless-stopped
    env_file:
      - ./bluesky.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.bsky.rule=Host(`bsky.{{ vault_stack_domain }}`)
    volumes:
      - "./data:/pds"
    networks:
      - Public