version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.17.3
    container_name: Gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
    env_file: 
      - ./.senv
    restart: always
    networks:
      - gitea
    volumes:
      - ./Data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2229:22"
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: MariaDB
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    env_file: 
      - ./.senv
    networks:
      - gitea
    volumes:
      - ./mysql:/var/lib/mysql