version: "2.3"

services:
  backup:
    container_name: DB-Auto-Backup
    image: ghcr.io/realorangeone/db-auto-backup:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./Backups:/var/backups"
    environment:
      - HEALTHCHECKS_HOST=HOST   #specify if not using healthcheks.io
      - HEALTHCHECKS_ID=id       #ID of Healthchek


#https://github.com/RealOrangeOne/docker-db-auto-backup