---
- name: Create beszel_agent directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0750"
  loop:
    - "{{ beszel_agent_data_dir }}"

- name: Deploy beszel_agent compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ beszel_agent_data_dir }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    mode: "0640"
  notify: restart beszel_agent

- name: Start beszel_agent stack
  community.docker.docker_compose_v2:
    project_src: "{{ beszel_agent_data_dir }}"
    state: present
