---
- name: Create portainer directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0750"
  loop:
    - "{{ portainer_data_dir }}"

- name: Deploy portainer compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ portainer_data_dir }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    mode: "0640"
  notify: restart portainer

- name: Start portainer stack
  community.docker.docker_compose_v2:
    project_src: "{{ portainer_data_dir }}"
    state: present
