---
- name: Create spoolman directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0750"
  loop:
    - "{{ spoolman_data_dir }}"

- name: Deploy spoolman compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ spoolman_data_dir }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    mode: "0640"
  notify: restart spoolman

- name: Start spoolman stack
  community.docker.docker_compose_v2:
    project_src: "{{ spoolman_data_dir }}"
    state: present
