---
- name: Create receipt_wrangler directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0750"
  loop:
    - "{{ receipt_wrangler_data_dir }}"

- name: Deploy receipt_wrangler compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ receipt_wrangler_data_dir }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    mode: "0640"
  notify: restart receipt_wrangler

- name: Start receipt_wrangler stack
  community.docker.docker_compose_v2:
    project_src: "{{ receipt_wrangler_data_dir }}"
    state: present
