---
- name: Create ntfy directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0750"
  loop:
    - "{{ ntfy_data_dir }}"

- name: Deploy ntfy compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ ntfy_data_dir }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    mode: "0640"
  notify: restart ntfy

- name: Start ntfy stack
  community.docker.docker_compose_v2:
    project_src: "{{ ntfy_data_dir }}"
    state: present
