---
# Ansible Galaxy dependencies
# Install with: ansible-galaxy install -r requirements.yml

collections:
  - name: ansible.windows
  - name: community.windows
  - name: community.general
  - name: community.docker
  - name: ansible.posix
    version: ">=1.5.4"
  - name: devsec.hardening

roles:
  - name: geerlingguy.docker
  - name: geerlingguy.ntp
  - name: artis3n.tailscale
