---
actual_budget_image_version: latest
actual_budget_data_dir: "{{ docker_root }}/actual_budget"
actual_budget_port: 5006
actual_budget_domain: "budget.int.jps.sh"
actual_budget_traefik_middlewares:
  - "tailscale-only@file"
