---
- name: Create pgbackweb directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0750"
  loop:
    - "{{ pgbackweb_data_dir }}"

- name: Deploy pgbackweb compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ pgbackweb_data_dir }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    mode: "0640"
  notify: restart pgbackweb

- name: Start pgbackweb stack
  community.docker.docker_compose_v2:
    project_src: "{{ pgbackweb_data_dir }}"
    state: present
